### PR TITLE
Added new quotes

### PR DESCRIPTION
**Pull request by Baibhab97**

### CODE REVIEW

**Comment by devcer** [comment]
Thank you for the PR.
As mentioned in #1

* Add atleast 5+ quotes with tags, moods and feel to get your PR merged

**Comment by Baibhab97** [comment]
@devcer I have added 5 quotes. Please accept the PR.

**Comment by devcer** [comment]
@Baibhab97 Add few more tags. Adding one tag for a caption won't be helpful for the data we are trying to collect.

**Comment by Baibhab97** [comment]
@devcer Sure. I will do the necessary changes and raise PR.

**Comment by Baibhab97** [comment]
@devcer I have added multiple tags. Please check and let me know if anything else needs to be changed.

**Review by devcer — APPROVED** [review]

**Pull request merged**
